#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-gtksourceview-soname3
Version  : 3.24.7
Release  : 22
URL      : https://download.gnome.org/sources/gtksourceview/3.24/gtksourceview-3.24.7.tar.xz
Source0  : https://download.gnome.org/sources/gtksourceview/3.24/gtksourceview-3.24.7.tar.xz
Summary  : Libraries and include files for GtkSourceView
Group    : Development/Tools
License  : LGPL-2.1
Requires: compat-gtksourceview-soname3-data
Requires: compat-gtksourceview-soname3-lib
Requires: compat-gtksourceview-soname3-doc
Requires: compat-gtksourceview-soname3-locales
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : go
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : itstool
BuildRequires : libxslt-bin
BuildRequires : meson
BuildRequires : ninja
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : python3
BuildRequires : vala
BuildRequires : vala-bin
BuildRequires : valgrind
Patch1: cve-2017-14108.patch

%description
GtkSourceview is a library that adds syntax highlighting,
line numbers, and other programming-editor features.
GtkSourceView specializes these features for a code editor.

%package data
Summary: data components for the compat-gtksourceview-soname3 package.
Group: Data

%description data
data components for the compat-gtksourceview-soname3 package.


%package dev
Summary: dev components for the compat-gtksourceview-soname3 package.
Group: Development
Requires: compat-gtksourceview-soname3-lib
Requires: compat-gtksourceview-soname3-data
Provides: compat-gtksourceview-soname3-devel

%description dev
dev components for the compat-gtksourceview-soname3 package.


%package doc
Summary: doc components for the compat-gtksourceview-soname3 package.
Group: Documentation

%description doc
doc components for the compat-gtksourceview-soname3 package.


%package lib
Summary: lib components for the compat-gtksourceview-soname3 package.
Group: Libraries
Requires: compat-gtksourceview-soname3-data

%description lib
lib components for the compat-gtksourceview-soname3 package.


%package locales
Summary: locales components for the compat-gtksourceview-soname3 package.
Group: Default

%description locales
locales components for the compat-gtksourceview-soname3 package.


%prep
%setup -q -n gtksourceview-3.24.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523380290
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1523380290
rm -rf %{buildroot}
%make_install
%find_lang gtksourceview-3.0

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
%exclude /usr/lib64/girepository-1.0/GtkSource-3.0.typelib
%exclude /usr/share/gir-1.0/GtkSource-3.0.gir
%exclude /usr/share/gtksourceview-3.0/language-specs/R.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/abnf.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/actionscript.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/ada.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/ansforth94.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/asp.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/automake.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/awk.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/bennugd.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/bibtex.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/bluespec.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/boo.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/c.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/cg.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/changelog.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/chdr.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/cmake.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/cobol.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/cpp.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/cpphdr.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/csharp.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/css.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/csv.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/cuda.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/d.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/def.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/desktop.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/diff.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/docbook.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/dosbatch.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/dot.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/dpatch.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/dtd.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/dtl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/eiffel.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/erlang.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/fcl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/forth.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/fortran.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/fsharp.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/gap.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/gdb-log.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/genie.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/glsl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/go.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/groovy.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/gtk-doc.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/gtkrc.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/haddock.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/haskell-literate.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/haskell.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/haxe.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/html.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/idl-exelis.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/idl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/imagej.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/ini.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/j.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/jade.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/java.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/javascript.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/json.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/julia.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/kotlin.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/language.dtd
%exclude /usr/share/gtksourceview-3.0/language-specs/language.rng
%exclude /usr/share/gtksourceview-3.0/language-specs/language2.rng
%exclude /usr/share/gtksourceview-3.0/language-specs/latex.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/lex.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/libtool.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/llvm.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/logcat.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/lua.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/m4.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/makefile.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/mallard.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/markdown.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/matlab.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/maxima.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/mediawiki.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/meson.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/modelica.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/mxml.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/nemerle.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/netrexx.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/nsis.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/objc.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/objj.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/ocaml.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/ocl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/octave.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/ooc.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/opal.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/opencl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/pascal.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/perl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/php.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/pig.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/pkgconfig.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/po.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/prolog.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/protobuf.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/puppet.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/python.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/python3.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/rpmspec.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/rst.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/ruby.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/rust.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/scala.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/scheme.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/scilab.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/sh.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/sml.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/sparql.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/sql.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/sweave.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/swift.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/systemverilog.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/t2t.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/tcl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/tera.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/texinfo.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/thrift.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/toml.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/vala.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/vbnet.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/verilog.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/vhdl.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/xml.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/xslt.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/yacc.lang
%exclude /usr/share/gtksourceview-3.0/language-specs/yaml.lang
%exclude /usr/share/gtksourceview-3.0/styles/classic.xml
%exclude /usr/share/gtksourceview-3.0/styles/cobalt.xml
%exclude /usr/share/gtksourceview-3.0/styles/kate.xml
%exclude /usr/share/gtksourceview-3.0/styles/oblivion.xml
%exclude /usr/share/gtksourceview-3.0/styles/solarized-dark.xml
%exclude /usr/share/gtksourceview-3.0/styles/solarized-light.xml
%exclude /usr/share/gtksourceview-3.0/styles/styles.rng
%exclude /usr/share/gtksourceview-3.0/styles/tango.xml

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/gtksourceview-3.0/gtksourceview/completion-providers/words/gtksourcecompletionwords.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksource.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceautocleanups.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcebuffer.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcecompletion.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcecompletioncontext.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcecompletioninfo.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcecompletionitem.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcecompletionproposal.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcecompletionprovider.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceencoding.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcefile.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcefileloader.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcefilesaver.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcegutter.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcegutterrenderer.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcegutterrendererpixbuf.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcegutterrenderertext.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcelanguage.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcelanguagemanager.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcemap.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcemark.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcemarkattributes.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceprintcompositor.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceregion.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcesearchcontext.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcesearchsettings.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcespacedrawer.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcestyle.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcestylescheme.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcestyleschemechooser.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcestyleschemechooserbutton.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcestyleschemechooserwidget.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcestyleschememanager.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcetag.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourcetypes.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceundomanager.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceutils.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceversion.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceview-enumtypes.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceview-typebuiltins.h
%exclude /usr/include/gtksourceview-3.0/gtksourceview/gtksourceview.h
%exclude /usr/lib64/libgtksourceview-3.0.so
%exclude /usr/lib64/pkgconfig/gtksourceview-3.0.pc

%files doc
%defattr(-,root,root,-)
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceBuffer.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceCompletion.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceCompletionContext.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceCompletionInfo.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceCompletionItem.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceCompletionProposal.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceCompletionProvider.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceCompletionWords.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceEncoding.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceFile.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceFileLoader.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceFileSaver.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceGutter.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceGutterRenderer.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceGutterRendererPixbuf.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceGutterRendererText.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceLanguage.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceLanguageManager.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceMap.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceMark.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceMarkAttributes.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourcePrintCompositor.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceRegion.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceSearchContext.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceSearchSettings.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceSpaceDrawer.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceStyle.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceStyleScheme.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceStyleSchemeChooser.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceStyleSchemeChooserButton.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceStyleSchemeChooserWidget.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceStyleSchemeManager.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceTag.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceUndoManager.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/GtkSourceView.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/annotation-glossary.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/api-index-full.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch01.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch02.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch03.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch04.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch05.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch06.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch07.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch08.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/ch09.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/gtksourceview-3.0-GtkSourceUtils.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/gtksourceview-3.0-Version-Information.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/gtksourceview-3.0.devhelp2
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/home.png
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/index.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/lang-reference.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/lang-tutorial.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/left-insensitive.png
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/left.png
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/object-tree.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/pt01.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/pt02.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/pt03.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/pt04.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/right-insensitive.png
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/right.png
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/style-reference.html
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/style.css
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/up-insensitive.png
%exclude /usr/share/gtk-doc/html/gtksourceview-3.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgtksourceview-3.0.so.1
/usr/lib64/libgtksourceview-3.0.so.1.8.0

%files locales -f gtksourceview-3.0.lang
%defattr(-,root,root,-)

